### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by ajbraus** [LucHighwalker/ts-node-starter#1]
Everything here is very tight, so I'll be extra picky here. 

1. Really professional 
1. Love the concept of a starter pack. You should share this more broadly in the TS community and maybe on hacker news? 
1. in your user interface, `verified` as a Boolean is not as good as `verfiedAt` as a Date. 
1. You can use {timestamps: true} to manage createdAt and updatedAt for you.
1. `IUser` and `IUserModel` are pretty weird names, why not `UserInterface` and `User`? or better yet `userParams` and `User`. Might be more conventional/readable/searchable.
1. For speed's sake, you should respond to the sign-up route before sending the welcome email. Emails can take full seconds to send. Don't make the response wait for the email.
1. You bloat out your code a lot with the `if (err) {}` being on multiple lines. If it only has one statement `reject(err)` just put it on one line and save yourself the length. You could also use return statements to avoid having to state the `else` case. Just return reject(err). 
1.  Why not use async/await in your controller? 
1. In controllers as well, there is some bloat putting contents of an object on their own line. Makes things harder to read:

```js
    this.router.get('/user', async (req, res) => {
      try {
        const token = req.get('token');
        const user = await auth.getUser(token);
        res.status(200).json({
          user
        });
      } catch (error) {
        res.status(401).json({
          error: error.message
        });
      }
    });
```

vs. 

```js
    this.router.get('/user', async (req, res) => {
      try {
        const token = req.get('token');
        const user = await auth.getUser(token);

        return res.status(200).json({ user });
      } catch (error) {
        return res.status(401).json({ error: error.message });
      }
    });
```

second one is more semantic and readable. Return statements help too b/c they highlight where the logic terminates.

**Comment by LucHighwalker** [comment]
Thanks for the feedback Braus!

I definitely plan on sharing it with the TS community as a whole as soon as
the CLI <https://www.npmjs.com/package/ts-node-cli> is a bit more fleshed
out and reliable.

using verifiedAt instead of a boolean is a really good idea! I'll
definitely do that.

I've had issues in the past with timestamps being unreliable, it would
sometimes save as zeroed unix time. So I just manage it on my own instead.

I'll definitely implement not having to wait for the email to send for the
signup response. But how would I go about receiving mailgun errors if there
are any. Should I just log them in a different log file?

I don't use async await in my controllers, because mongoose promises are
not true promises, so I generally prefer sticking to callback functions
when dealing with mongoose. I know they work similarly, I just prefer
sticking to callbacks and wrapping those in a promise function.

the if (err) {}  statements being on multiple lines is typescript
convention, or rather single line if statements are against typescript
convention, and the default tslint rules will multiline it automatically.
Same applies to objects being on their own line. I add the else block
solely to be more explicit, a habit I picked up during my internship before
coming make school. And personally, I find it easier to read that way.
Though I agree with adding return statements in front of the res to
highlight logic termination.

Thank you again for the feedback!
- Luc

**Comment by ajbraus** [comment]
Your malign errors will be listed in a log in mailgun (That’s the easiest solution). Maybe you can have mailgun send you an email for errors?

You might look at mongorita as a replacement for mongoose if you want an ODM that responds with promises.

Definitely follow whatever style you prefer. At this point it is just that, style differences!


Warmly,

Adam Braus
608-770-0230
